#!/bin/sh

export PYSUPSICTRL="$( cd "$(dirname "$0")" ; pwd )"
export PYEDITOR=emacs

if [ -n "$PYTHONPATH" ] ; then
    PYTHONPATH=":$PYTHONPATH"
fi

export PYTHONPATH="$PYSUPSICTRL/resources/blocks/rcpBlk$PYTHONPATH"

PYSUPSICTRL_LINKS="$HOME/Documents/pysupsictrl/toolbox"
if [ "$1" = '-s' ] ; then
    shift
    mkdir -p "$PYSUPSICTRL_LINKS"
    rm -f "$PYSUPSICTRL_LINKS/supsisim"
    ln -s "$PYSUPSICTRL/toolbox/supsisim/src" "$PYSUPSICTRL_LINKS/supsisim"
    rm -f "$PYSUPSICTRL_LINKS/supsictrl"
    ln -s "$PYSUPSICTRL/toolbox/supsictrl/src" "$PYSUPSICTRL_LINKS/supsictrl"
fi

if [ -e "$PYSUPSICTRL_LINKS" ] ; then
    export PYTHONPATH="$PYSUPSICTRL_LINKS:$PYTHONPATH"
fi

if [ -t 0 -a -t 1 ]
then
    /usr/bin/python3 "$PYSUPSICTRL/BlockEditor/pysimCoder.py" "$@"
else
    /usr/bin/python3 "$PYSUPSICTRL/BlockEditor/pysimCoder.py" > /tmp/pysimCoder.log "$@"
fi

if [ $? -ne 0 ] ; then
   echo >&2 "consider to run $0 with -s argument to setup links in $PYSUPSICTRL_LINKS"
fi
